#!/bin/bash

#SEQUENCE='AGCCGGAAGCCTATGTACCGAGTTCCGACACTTTCATTGAGAAAGATGCCTCAGCTCTGTTACAGGTCACTAATACCATCTAAGTAGTTGATTCATAGTGACTGCATATGTTGTGTTTTACAGTATTATGTAGTCTGTTTTTTATGCAAAATCTAATTTAATATATTGATATTTATATCATTTTACGTTTCTCGTTCAGCTTTTTTATACTAACTTGAGCGAAACGGGAAGGGTTTTCACCGATATCACCGAAACGCGCGAGGCAGCTGTATGGCATGAAAGAGTTCTTCCCGGAAAACGCGGTGGAATATTTCGTTTCCTACTACGACTACTATC'
SEQUENCE='GTAGTTGATTCATAGTGACTGCATATGTTGTGTTTTACAGTATTATGTAGTCTGTTTTTTATGCAAAATCTAATTTAATATATTGATATTTATATCATTTTACGTTTCTCGTTCAGCTTTTTTATACTAACTTGAGCGAAACGGGAAGGGTTTTCACCGATATCACCGAAACGCGCGAGGCAGCTGTATGGCATGAAAGAGTTCTTCCCGGAAAACGCGGTGGAATATTTCGTTTCCTACTACGACTACTATCAGCCGGAAGCCTATGTACCGAGTTCCGACACTTTCATTGAGAAAGATGCCTCAGCTCTGTTACAGGTCACTAATACCATCTAA'

STDDIR="bplist_configs"
TRDDIR="par_trd-configs"

declare -a INCONS
for FILE in ${STDDIR}/*.txt;
do
 NAME=( "${FILE##*/}" )
 INCONS+=( "${NAME%.txt}" )
 unset NAME
done

for ((i=0; i<=336; i++));
do

 for INCON in ${INCONS[@]};
 do
  
  echo "$INCON"
  NAME=${INCON}_seq${i}
  
  # Slither the sequence AND add additional base at end for circular sequence
  SEQ=${SEQUENCE:${i}}${SEQUENCE::${i}}
  SEQ=${SEQ}${SEQ:0:1}
 
 
 # Make par file for optimization
 emDNA_parser \
 --bp-list-input=${STDDIR}/${INCON}.txt \
 --bp-list-sequence=${SEQ} \
 --get-x3DNA-params>${TRDDIR}/${NAME}.par
 
 done
done

# -----------------------------------------------------------------------------------------------------------------------------------------
